---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      containers:
      - name: ace
        image: ibmcom/ace:latest
        env:
          - name: LICENSE
            value: accept
          - name: ACE_SERVER_NAME
            value: ACE_SERVER
        ports:
        - containerPort: 7600
        - containerPort: 7800
        - containerPort: 7843
        
---

apiVersion: v1
kind: Service
metadata:
  name: ace-service
spec:
  type: NodePort
  selector:
    app: ace
  ports:
    - name: passthrough 
      protocol: TCP
      port: 7600
      targetPort: 7600
    - name: nio
      protocol: TCP
      port: 7800
      targetPort: 7800
    - name: https
      protocol: TCP
      port: 7843
      targetPort: 7843

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress


